"""Build data/store_layout.json from the per-store configs.

store_layout.json is what the API reads for (a) open hours (the DEAD_ZONE anomaly)
and (b) the canonical zone list. It is NOT created automatically by the pipeline,
so this script generates it deterministically from each store's zones.json +
clips_manifest.json (registered in pipeline/config/stores.json). No model/Gemini is
needed — zones.json already carries zone_type / is_revenue_zone / zone_name.

    python scripts/build_store_layout.py            # writes data/store_layout.json
    python scripts/build_store_layout.py --out -    # print to stdout (dry run)

Existing per-store open_hours / city in the current layout are preserved.
"""
from __future__ import annotations

import argparse
import json
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


def _load(path: str, default):
    try:
        with open(os.path.join(ROOT, path), encoding="utf-8") as fh:
            return json.load(fh)
    except (OSError, json.JSONDecodeError):
        return default


def build() -> dict:
    registry = (_load("pipeline/config/stores.json", {}) or {}).get("stores", {})
    existing = (_load("data/store_layout.json", {}) or {}).get("stores", {})

    stores: dict[str, dict] = {}
    for key, reg in registry.items():
        cfg = reg.get("config_dir", f"pipeline/config/{key}")
        manifest = _load(f"{cfg}/clips_manifest.json", [])
        zones_cfg = _load(f"{cfg}/zones.json", {})
        store_id = reg.get("store_id", key)
        prev = existing.get(store_id, {})

        cameras = {c.get("role", c["camera_id"]): c["camera_id"]
                   for c in manifest if isinstance(c, dict) and c.get("camera_id")}

        zones, seen = [], set()
        for cam, zmap in zones_cfg.items():
            if cam.startswith("_") or not isinstance(zmap, dict):
                continue
            for zid, z in zmap.items():
                if not isinstance(z, dict) or not z.get("polygon") or zid in seen:
                    continue
                seen.add(zid)
                zones.append({
                    "zone_id": zid,
                    "zone_name": z.get("zone_name", zid),
                    "zone_type": z.get("zone_type", "SHELF"),
                    "is_revenue_zone": bool(z.get("is_revenue_zone", not z.get("is_staff_zone"))),
                    "camera_id": cam,
                })

        stores[store_id] = {
            "store_id": store_id,
            "city": prev.get("city", ""),
            # preserve authored hours; default to always-open (never suppress dead-zone)
            "open_hours": prev.get("open_hours", {"open": "00:00", "close": "23:59"}),
            "cameras": cameras,
            "zones": zones,
        }
    return {"_comment": "Generated by scripts/build_store_layout.py from each store's "
                        "zones.json + clips_manifest.json (registry: pipeline/config/stores.json).",
            "stores": stores}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default="data/store_layout.json", help="output path, or - for stdout")
    a = ap.parse_args()
    layout = build()
    text = json.dumps(layout, indent=2)
    if a.out == "-":
        print(text)
        return
    out = os.path.join(ROOT, a.out)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8") as fh:
        fh.write(text + "\n")
    n_zones = sum(len(s["zones"]) for s in layout["stores"].values())
    print(f"Wrote {out}  ({len(layout['stores'])} stores, {n_zones} zones)")


if __name__ == "__main__":
    main()
